INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (1, N'Saadman', N'Sydney', 33.87, -150.89, N'Good weather today')
INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (2, N'Hannah', N'Melbourne', 44.98, 178.8, N'Nice city!')
INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (3, N'Jarrad', N'Canberra', 78.8, 199, N'Boring city')
INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (4, N'Paul', N'Darwin', 160.9, 200, N'Too many crocodiles here')
INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (5, N'Silvan', N'Tasmania', 70, 300, N'People are nice here')
INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (6, N'Alexia', N'Adelaide', NULL, NULL, N'Nice city')
INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (7, N'Robert', N'Hobart', NULL, NULL, N'It''s lonely here')
INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (8, N'shs', N'Sydney', -33.8612, 151.1982, N'it''s hot today')
INSERT INTO [dbo].[UserNote] ([id], [userName], [city], [lattitude], [longitude], [note]) VALUES (9, N'silvan', N'Sydney', -33.8612, 151.1982, N'I prefer the swiss climate')
